baseurl = "http://blog.nheer.io/"
languageCode = "en-us"
title = "Niklas' Blog"
theme = "nh"


pygmentsuseclasses = true


[permalinks]
	post = "/:year/:month/:day/:slug"

[params]
	name = "Niklas Heer"
	DateForm = "2. Jan 2006"
	DateFormPost = "2. January 2006"
	description = "My personal blog."
	copyright = "© 2015 Niklas Heer<br /> [CC BY-NC-SA](http://creativecommons.org/licenses/by-nc-sa/3.0/) Some rights reserved."

	# Enable comments by entering your Disqus shortname
	disqusshortname = "niklas_heer"
	# Enable Google Analytics by entering your tracking code
	googleanalytics = ""

	# Links to newer/older blog posts
	newer = "Newer"
	older = "Older"

[params.offcanvas]
	# Menu items
	title = "Hi, I'm Niklas Heer."
	bio = "I love to write stuff about things that grab my attention!"
	subscribe = "Subscribe"
	followme = "Follow me on"
	mysites = "Other interesting sites"
	links = "Links"

	[[params.offcanvas.linksentries]]
		name = "About me"
		url = "http://nheer.io"

	[[params.offcanvas.linksentries]]
		name = "Imprint"
		url = "http://nheer.io#imprint"

	[[params.offcanvas.linksentries]]
		name = "Disclaimer"
		url = "http://nheer.io#disclaimer"

	[[params.offcanvas.linksentries]]
		name = "Privacy"
		url = "http://nheer.io#privacy"

	
	[[params.offcanvas.socialnetworks]]
		name = "Github"
		url = "//github.com/niklas-heer"

	[[params.offcanvas.socialnetworks]]
		name = "Twitter"
		url = "//twitter.com/niklas_heer"


	

	[[params.offcanvas.mysitesentries]]
		name = "Linux statt Windows"
		url = "https://linux-statt-windows.org"

