name = "nh"
license = "MIT"
licenselink = "//github.com/niklas-heer/blog/blob/master/LICENSE"
description = " A minimal theme perfect for dev-savvy bloggers."
homepage = "//github.com/niklas-heer/blog/tree/master/themes/nh"
tags = ["blog", "minimal", "syntax highlighting", "Disqus", "Google Analytics"]
features = ["", ""]
min_version = 0.14

[author]
  name = "niklas-heer"
  homepage = "//github.com/niklas-heer"

[original]
  name = "digitalcraftsman"
  homepage = "//github.com/digitalcraftsman/hugo-hikari-theme"